name = "hatonrinoweb"
main = "worker.js"
compatibility_date = "2026-04-13"
compatibility_flags = ["nodejs_compat"]
account_id = "7fbf3fb07f07881c9aaa70befc0c5da0"
workers_dev = true

[assets]
directory = "./"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BBS"
id = "cb52c0dad6a5473a85d97af3275cebb0"
